### ISSUE TITLE
ES5 browsers not supported by queueing-subject by angular 8's legacy build

### ISSUE THREAD

**Issue by dklmuc** [ohjames/queueing-subject#22]
After upgrading to angular8 we were forcing the same problems as in #19. After the fix, tests show that it's not working in internet explorer 11.

minimal reproduction: https://github.com/dklmuc/queueing-subject-angular8

IE11 shows error in main-es5 bundle because of non ES5 compatible code:
`Ja=function(){return function(){}}();class $a extends M{constructor(){super(...arguments),this.queuedValues=[]}next(t){this.closed||this.observers.length?super.next(t):this.queuedValues.push(t)}_subscribe(t){const`

The same also when completly disable differential loading (changing target to es5 and remove browserlist file).

**Comment by ohjames** [comment]
Hm, your `browserlist` looks correct (unless `not dead` is taking precedence over `IE9-11`?), so it looks like angular's legacy build process is incorrectly sourcing from `module` instead of `main` even for the legacy build. Could it be a bug with angular-cli? Yet it manages to deal with compiling the appropriate angular code so... maybe `queueing-subject` missing something from `package.json`?

**Comment by ohjames** [comment]
Hm:

From https://auth0.com/blog/angular-8-differential-loading/

> One very important note about this: See that not IE 9-11 part? If you need to support those browsers, you can remove the not, but it comes at a price. Those versions of Internet Explorer can’t take advantage of differential loading, so it will be disabled.

**Comment by ohjames** [comment]
So given that, if you want to support IE9-11, it looks like you can't use differential loading and must set your `target` property back from `es2015` to `es5` in your tsconfig.js.

If that page is incorrect then please reopen this bug, otherwise it looks like a general problem with supporting IE9-11.

**Comment by dklmuc** [comment]
I shouldn't mention differential loading at all ;-) I just stumbled over the problem when testing this new feature.

But also when I simply target ES5 in tsconfig, the builded bundle is not ES5-compatible. You see stuff like `extens` or spread operator in it.

so in short:
#19 fixed ES2015 target, but destroyed ES5 target in angular8

**Comment by ohjames** [comment]
Hm, is this a problem with Angular's build system?

**Comment by dklmuc** [comment]
I don't think so. We have got a very large project with around 20 modules and hundreds of components.

So upgrading to angular 8 kills the IE11 compatibility. After digging a lot around by removing all modules and readding them, I was able to identify our chat module as the root cause. So our app is working completly with angular8 beside of the chat.

Then I did a plain new project with latest CLI, builded it for ES5 and it was working in IE11. Adding queueing-subject to this app (like in reproduction repo) results immediatly in the given error. Seems like the build process is adding the es2015 version of queueing-subject to its bundle, also when the target is set to es5.

**Comment by ohjames** [comment]
If other libraries that you are using are also providing es2015 libraries via the `package.json` `module` attribute then you could check them out to see what they are doing differently to this package. If not... then it could be angular. I thought having `main` point to the ES5 code and having `module` point to the ES2015 code was the way to go.

**Comment by ohjames** [comment]
Maybe it could be due to the ES2015 code being in a subdirectory of the ES5 code? (Although that really shouldn't make a difference)

**Comment by ohjames** [comment]
It could also be related to the tsconfig somehow?

**Comment by ohjames** [comment]
Hm maybe `module` should point to ES5 code with module imports and `jsnext:main` should point to ES2015+ code.

**Comment by dklmuc** [comment]
Unfortunately I'm not deep into this whole packaging stuff ;-)

But I played a little bit around and looking at other libraries  we are using.

When changing package.json of queueing-subject to:
```
  "main": "lib/index.js",
  "module": "lib/index.js",
  "es2015": "lib/es2015/index.js",
```
then rebuild lib and doing a new build of the test repo, it seems to work as it should.

**Comment by ohjames** [comment]
Cool, sounds like "es2015"  is the right property if it works in both builds for you. I'd like to confirm for myself though, could you give an example of another open source project that uses this property?

**Comment by dklmuc** [comment]
Wish I have some deeper knowledge of it to be more helpful.

Seen it in the installed version of https://github.com/mattlewis92/angular-calendar (choice was just alphabetical) that he is using a lot of different bundle types:
```
"main": "bundles/angular-calendar.umd.js",
"module": "fesm5/angular-calendar.js",
"es2015": "fesm2015/angular-calendar.js",
"esm2015": "esm2015/angular-calendar.js",
"esm5": "esm5/angular-calendar.js",
"fesm2015": "fesm2015/angular-calendar.js",
"fesm5": "fesm5/angular-calendar.js",
```

**Comment by ohjames** [comment]
@dklmuc Thanks for your help! I'll publish a new build shortly with the changes. For now I'll support `main`, `module` and `es2015`.

**Comment by ohjames** [comment]
Published `0.3.3` with the fixes, let me know if it works for you!

**Comment by dklmuc** [comment]
Sorry for the delayed answer but weather was too nice ;-)

I've checked v0.3.3 and all is working fine. I've also verified the bundle created by angular CLI, es5 main bundle contains the es5 queueing-subject code and also es2015 bundle is looking absolutely fine.

Thanks for the quick fix.

**Comment by ohjames** [comment]
Thanks for the bug report and your help.

**Comment by zhuangya** [comment]
for now, the typing file is missing :(

should we change [this line](https://github.com/ohjames/queueing-subject/blob/df089cca32d452806b4e53e944e15368cd3bf96d/package.json#L8) to something like `lib.es5/index` or, keep the `lib` dir?

**Comment by ohjames** [comment]
@zhuangya Fix is published now
